name: 功能请求 / Feature Request
description: 提交你想要的新功能
labels: ["Feature"]
title: "[Feature Request] "
body:
  - type: checkboxes
    attributes:
      label: 在开始之前 / Before starting
      options:
        - label: 我了解本 Repo 仅接受 HugoAura Aikari (涉及流量过滤、底层修改时依赖的组件) 的功能请求
          required: true
        - label: 我知晓, 如果这是关于 HugoAura-Main 的功能请求, 我应该前往 [HugoAura-Main Issues](https://github.com/HugoAura/Seewo-HugoAura/issues) 提交 Feature Request
          required: true
        - label: 我知晓, 如果这是关于 HugoAura 安装器的功能请求, 我应该前往 [HugoAura-Install Issues](https://github.com/HugoAura/HugoAura-Install/issues) 提交 Feature Request
          required: true
        - label: 我知晓, 如果我将 Issue 提交到了错误的 Repo, 可能会引发开发者响应速度降低 / Issue 被忽略 / Issue 被 Close as duplicate / Issue 被 Transfer 等情况
          required: true

  - type: textarea
    attributes:
      label: 概述 / Overview
      description: 简述你想要的新功能, 需要它做什么
      placeholder:
    validations:
      required: true

  - type: textarea
    attributes:
      label: 背景 (可选) / Background info (Optional)
      description: 有哪些因素让你想到了这个新功能? 它为什么对用户体验至关重要?
      placeholder:
    validations:
      required: false

  - type: textarea
    attributes:
      label: 具体需求 / Detail Requirements
      description: 请详细描述具体希望实现哪些目标, 以及提出你认为可能的实现思路
      placeholder: |
        我希望能够实现...
        具体来讲, 包含:
        1. 实现 XXX
        2. XXXXXX
        3. XXXXXX
    validations:
      required: true

  - type: input
    attributes:
      label: HugoAura Aikari 版本 / HugoAura Aikari version
      description: 创建此 Issue 时的最新 HugoAura Aikari 版本
    validations:
      required: true

  - type: checkboxes
    id: confirms
    attributes:
      label: 提交前请确认 / Confirm before submit
      options:
        - label: 我已经在 [HugoAura Aikari Issues](https://github.com/HugoAura/HugoAura-Aikari/issues) 中查询过相关关键词, 并确定此功能请求是唯一的。
          required: true

  - type: textarea
    id: extraDesc
    attributes:
      label: 其他信息 (可选) / Additional info (Optional)
